#ifndef SYSTEMFUNCTIONALITY_GLOBAL_H
#define SYSTEMFUNCTIONALITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMFUNCTIONALITY_LIBRARY)
#  define SYSTEMFUNCTIONALITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMFUNCTIONALITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMFUNCTIONALITY_GLOBAL_H
