#ifndef UIRESOURCES_GLOBAL_H
#define UIRESOURCES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UIRESOURCES_LIBRARY)
#  define UIRESOURCESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UIRESOURCESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UIRESOURCES_GLOBAL_H
